version: '3.4'

networks:
  default:
    driver: bridge
services:
  api:
    build: ./Projet_ex1/backend
    volumes:
      - "./Projet_ex1/backend/:/app/backend"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
    ports:
    - "8000:8000"

  db:
    build: .
    command: ["mongod", "--dbpath", "/app/data"]
    ports:
    - "27017:27017"

  front:
    build: ./Projet_ex1/frontend
    ports:
      - "3000:3000"